-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Occasion exposing (competitors, events, id, name, teams)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


competitors : SelectionSet decodesTo Api.Object.Competitor -> SelectionSet (Maybe (List decodesTo)) Api.Object.Occasion
competitors object_ =
    Object.selectionForCompositeField "competitors" [] object_ (identity >> Decode.list >> Decode.nullable)


events : SelectionSet decodesTo Api.Object.Event -> SelectionSet (Maybe (List decodesTo)) Api.Object.Occasion
events object_ =
    Object.selectionForCompositeField "events" [] object_ (identity >> Decode.list >> Decode.nullable)


id : SelectionSet Api.ScalarCodecs.Id Api.Object.Occasion
id =
    Object.selectionForField "ScalarCodecs.Id" "id" [] (Api.ScalarCodecs.codecs |> Api.Scalar.unwrapCodecs |> .codecId |> .decoder)


name : SelectionSet String Api.Object.Occasion
name =
    Object.selectionForField "String" "name" [] Decode.string


teams : SelectionSet decodesTo Api.Object.Team -> SelectionSet (Maybe (List decodesTo)) Api.Object.Occasion
teams object_ =
    Object.selectionForCompositeField "teams" [] object_ (identity >> Decode.list >> Decode.nullable)
