-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.OccasionResult exposing (points, score, team)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


points : SelectionSet Int Api.Object.OccasionResult
points =
    Object.selectionForField "Int" "points" [] Decode.int


score : SelectionSet (List Int) Api.Object.OccasionResult
score =
    Object.selectionForField "(List Int)" "score" [] (Decode.int |> Decode.list)


team : SelectionSet decodesTo Api.Object.Team -> SelectionSet decodesTo Api.Object.OccasionResult
team object_ =
    Object.selectionForCompositeField "team" [] object_ identity
