-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object exposing (Competitor(..), Event(..), Marble(..), Occasion(..), Team(..))


type Competitor
    = Competitor


type Event
    = Event


type Marble
    = Marble


type Occasion
    = Occasion


type Team
    = Team
